plan-action:
  - ".github/workflows/pr_opex_api_trial.yaml"
  - ".github/workflows/call_pr_opex_api.yml"
apply-action:
  - ".github/workflows/opex_api_trial.yaml"
  - ".github/workflows/call_opex_api.yml"
management:
  - "apps/functions-subscription/api/public.yaml"
  - "apps/functions-subscription/.opex/management/**"