plan-action:
  - ".github/workflows/pr_opex_api_trial.yaml"
  - ".github/workflows/call_pr_opex_api.yml"
apply-action:
  - ".github/workflows/opex_api_trial.yaml"
  - ".github/workflows/call_opex_api.yml"
management:
  - "infra/resources/modules/commons/api/ts_management/v1/_openapi.yaml"
  - "apps/functions-subscription/.opex/management/**"
