nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

# To ensure that each workspace declares the dependencies it uses, disable
# hoisting. Packages won't be hoisted past the workspace that depends on them.
nmHoistingLimits: workspaces
