openapi: 3.0.1
info:
  version: 0.0.0
  title: Trial System API
  description: |
    Documentation of the Trial System Subscription function.
servers: 
  - url: https://ts-p-itn-management-fn-01.azurewebsites.net
security:
  - ApiKeyAuth: []
paths:
  /info:
    get:
      operationId: info
      responses:
        '200':
          $ref: '#/components/responses/200Info'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /trials:
    post:
      operationId: createTrial
      description: Create a new Trial initiative
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrial'
      responses:
        '200':
          $ref: '#/components/responses/200Trial'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalServerError'


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Functions-Key

  schemas:
    ProblemJson:
      $ref: 'https://raw.githubusercontent.com/pagopa/io-functions-commons/v29.0.0/openapi/definitions.yaml#/ProblemJson'
    ApplicationInfo:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    TrialId:
      type: string
      description: Unique identifier of the trial.
      minLength: 1
    CreateTrial:
      type: object
      properties:
        name:
          type: string
          description: The Trial initiative's name
          minLength: 1
        description:
          type: string
          description: The Trial initiative's extended description
          minLength: 1
        isEnabled:
          type: boolean
          description: Describe if a Trial initiative is enabled or not. If not provided Trial initiative is enabled by default
      required:
        - trialId
        - name

    CreatedTrial:
      type: object
      properties:
        trialId:
          $ref: '#/components/schemas/TrialId'
        isEnabled:
          type: boolean
          description: Describe if a Trial initiative is enabled or not
      required:
        - trialId
        - isEnabled

  responses:
    500InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemJson'
    400BadRequest:
      description: Bad Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemJson'
    401Unauthorized:
      description: Unauthorized
    404NotFound:
      description: Not Found
    200Info:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApplicationInfo'
    200Trial:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatedTrial'