openapi: 3.0.3
info:
  version: 0.0.0
  title: Trial System API
  description: |
    Documentation of the Trial System Subscription function.
servers:
  - url: https://ts-p-itn-subscription-fn-01.azurewebsites.net
security:
  - ApiKeyAuth: []
paths:
  /info:
    get:
      operationId: info
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationInfo'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /trials/{trialId}/subscriptions/{userId}:
    get:
      operationId: getSubscription
      summary: Get subscription detail
      description: >-
        Returns the details about the subscription of the specified user for
        the specified trial.
      parameters:
        - $ref: '#/components/parameters/pathTrialId'
        - $ref: '#/components/parameters/pathUserId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /trials/{trialId}/subscriptions:
    post:
      operationId: createSubscription
      summary: Create a subscription
      description: Subscribe the given user to the given trial.
      parameters:
        - $ref: '#/components/parameters/pathTrialId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscription'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '202':
          description: Accepted
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /trials/{trialId}/activation-job:
    parameters:
      - $ref: '#/components/parameters/pathTrialId'
    get:
      operationId: getActivationJob
      description: Get the activation job for the given trial
      summary: Get the activation job
      responses:
        '200':
          description: The activation job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivationJob'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
    put:
      operationId: updateActivationJob
      description: Update an activation job
      summary: Update an activation job
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateActivationJob'
      responses:
        '200':
          description: The activation job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivationJob'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
    post:
      operationId: createActivationJob
      description: Create the job to activate users for a given trial
      summary: Create the activation job
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActivationJob'
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized
        '404':
          description: Trial not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /trials:
    post:
      operationId: createTrial
      description: Create a trial
      summary: Create a trial
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrial'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartialTrial'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /trials/{trialId}:
    get:
      operationId: getTrial
      description: Get trial by id
      summary: Get a trial
      parameters:
        - $ref: '#/components/parameters/pathTrialId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trial'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Functions-Key
  parameters:
    pathTrialId:
      name: trialId
      in: path
      required: true
      schema:
        type: string
        minLength: 1
    pathUserId:
      name: userId
      in: path
      required: true
      schema:
        # Using the reference ($ref) to UserId breaks the client generator
        # For now duplicate the type
        type: string
        minLength: 1
    pathActivationJobId:
      name: activationJobId
      in: path
      required: true
      schema:
        type: string
        minLength: 1
  schemas:
    ProblemJson:
      $ref: 'https://raw.githubusercontent.com/pagopa/io-functions-commons/v29.0.0/openapi/definitions.yaml#/ProblemJson'
    ApplicationInfo:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    CreatedAt:
      $ref: 'https://raw.githubusercontent.com/pagopa/io-functions-commons/v29.0.0/openapi/definitions.yaml#/Timestamp'
    UpdatedAt:
      $ref: 'https://raw.githubusercontent.com/pagopa/io-functions-commons/v29.0.0/openapi/definitions.yaml#/Timestamp'
    UserId:
      type: string
      minLength: 1
    SubscriptionState:
      type: string
      description: |-
        - UNSUBSCRIBED: The user is not subscribed to the specified trial and does
            not have any access to the specified trial.
        - SUBSCRIBED: The user is subscribed to the specified trial and does
            not have any access to the specified trial. The system is going to
            activate the user if any slot for the trial is available.
        - ACTIVE: The user has the access to the specified trial.
        - DISABLED: The user does not have the access to the specified trial.
      enum:
        - UNSUBSCRIBED
        - SUBSCRIBED
        - ACTIVE
        - DISABLED
    CreateSubscriptionState:
      type: string
      description: |-
        - SUBSCRIBED: The user is subscribed to the specified trial and does
            not have any access to the specified trial. The system is going to
            activate the user if any slot for the trial is available.
        - ACTIVE: The user has the access to the specified trial.
      enum:
        - SUBSCRIBED
        - ACTIVE
    TrialId:
      type: string
      description: Unique identifier of the trial.
      minLength: 1
    TrialName:
      type: string
      description: The name of the trial
      minLength: 1
    TrialDescription:
      type: string
      description: The description of the trial
    UsersToActivate:
      type: integer
      minimum: 1
      format: int32
      description: The total number of users to activate
    CreateSubscription:
      description: >
        Payload to create a subscription.
        If the `state` property is not provided, the subscription will have the
        `SUBSCRIBED` state. Otherwise, the subscription will be created with the
        provided state.
      type: object
      required:
        - userId
      properties:
        userId:
          $ref: '#/components/schemas/UserId'
        state:
          $ref: '#/components/schemas/CreateSubscriptionState'
    Subscription:
      type: object
      required:
        - trialId
        - userId
        - state
        - createdAt
        - updatedAt
      properties:
        trialId:
          $ref: '#/components/schemas/TrialId'
        userId:
          $ref: '#/components/schemas/UserId'
        state:
          $ref: '#/components/schemas/SubscriptionState'
        createdAt:
          $ref: '#/components/schemas/CreatedAt'
        updatedAt:
          $ref: '#/components/schemas/UpdatedAt'
    CreateActivationJob:
      type: object
      required:
        - usersToActivate
      properties:
        usersToActivate:
          $ref: '#/components/schemas/UsersToActivate'
    UpdateActivationJob:
      type: object
      required:
        - usersToActivate
      properties:
        usersToActivate:
          $ref: '#/components/schemas/UsersToActivate'
    ActivationJob:
      type: object
      required:
        - trialId
        - usersToActivate
        - usersActivated
      properties:
        trialId:
          $ref: '#/components/schemas/TrialId'
        usersActivated:
          type: integer
          format: int32
          minimum: 0
          description: The total number of activated users
        usersToActivate:
          $ref: '#/components/schemas/UsersToActivate'
    SubscriptionEvent:
      type: object
      required:
        - trialId
        - userId
        - state
        - updatedAt
      properties:
        trialId:
          $ref: '#/components/schemas/TrialId'
        userId:
          $ref: '#/components/schemas/UserId'
        state:
          $ref: '#/components/schemas/SubscriptionState'
        updatedAt:
          $ref: '#/components/schemas/UpdatedAt'
    CreateTrial:
      type: object
      required:
        - name
      properties:
        name:
          $ref: '#/components/schemas/TrialName'
        description:
          $ref: '#/components/schemas/TrialDescription'
    TrialState:
      type: string
      description: |-
        - IN_PROGRESS: The Trial System is creating the resources related to the trial.
          The configuration is not yet completed.
        - CREATED: The Trial System created the resources for the trial.
      enum:
        - IN_PROGRESS
        - CREATED
    PartialTrial:
      type: object
      required:
        - id
        - state
      properties:
        id:
          $ref: '#/components/schemas/TrialId'
        state:
          $ref: '#/components/schemas/TrialState'
    Trial:
      type: object
      required:
        - id
        - name
        - state
      properties:
        id:
          $ref: '#/components/schemas/TrialId'
        name:
          $ref: '#/components/schemas/TrialName'
        description:
          $ref: '#/components/schemas/TrialDescription'
        state:
          $ref: '#/components/schemas/TrialState'
        queue:
          type: object
          description: All the information the caller must have in order to properly
            read events from the queue.
          required:
            - name
            - identity
          properties:
            name:
              type: string
              description: The name of the queue where the events are sent.
              minLength: 1
            identity:
              type: string
              description: >-
                The identifier of the Identity to use in order to read
                the events from the queue.

