name: Code Review Infra

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      # Trigger the workflow when resources are modified
      - "infra/resources"
      # Trigger the workflow when the involved workflows are modified
      - ".github/workflows/code_review_infra.yaml"
      - ".github/workflows/templates/infra_**"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Infrastructure Plan
    secrets: inherit
    with:
      environment: prod
      region: italynorth
      base_path: infra/resources
