name: Decorate PR

on:
  pull_request:

jobs:

  add_assignee:
    name: Add assignee
    runs-on: ubuntu-latest

    steps:
      - name: Assign PR
        uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e # v2.0.0
        with:
          configuration-path: '.github/auto-assign.yaml'
