name: "Deploy App Function"

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: Function App resource group name.
        required: true
      function_app_name:
        description: Function App name.
        required: true
      workspace_name:
        description: The name of the workspace to create the artifact for.
        required: true
        type: choice
        options:
          - functions-subscription
      environment:
        description: Environment where the artifact will be deployed.
        required: false
        default: 'prod'
        options:
          - prod

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@f09aec9635f1b6f550dd90d2d2581d3e5239b409
    secrets: inherit
    with:
      workspace_name: ${{ inputs.workspace_name }}
      environment: app-${{ inputs.environment }}
      resource_group_name: ${{ inputs.resource_group_name }}
      function_app_name: ${{ inputs.function_app_name }}
      health_check_path: "/info"
