name: "Deploy API App Function"

on:
  workflow_dispatch:
  push:
    tags:
      # Trigger this workflow when a tag `functions-subscription@<sem-ver>` is pushed
      # E.g.: `functions-subscription@1.2.3` triggers the workflow; `functions-subscription@1` does not.
      - 'functions-subscription@[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    name: Deploy API
    concurrency:
      # This value must be equals to the one set in the DX Workflow: https://github.com/pagopa/dx/blob/51ca1/.github/workflows/function_app_deploy.yaml#L36C10-L36C35
      group: ${{ github.workflow }}-cd
      # Override this configuration to prevent cancelling a running deploy.
      cancel-in-progress: false
    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@175afe715ca8830bd03554fe13e276a4e5092c25
    secrets: inherit
    with:
      workspace_name: functions-subscription
      environment: app-prod
      resource_group_name: ts-p-itn-api-rg-01
      web_app_name: ts-p-itn-api-func-01
