name: Opex Dashboard trial-system

on:
  push:
    branches:
      - main
    paths:
      - "apps/functions-subscription/api/*.yaml"
      - "infra/resources/modules/commons/api/**/*.yaml"
      - ".github/workflows/opex_api_session_manager.yaml"
      - ".github/workflows/call_opex_api.yml"
      - "apps/functions-subscription/.opex/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  filter:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    outputs:
      apply-action: ${{ steps.filter.outputs.apply-action }}
      management: ${{ steps.filter.outputs.management }}
    # Checks to see if openapi specs in the PR match one of the ones listed.
    # We can use the result to decide which job to run
    # With this type of filter we can avoid creating a lot of workflow files
    steps:
      # path-filters action requires checkout with push event
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 20
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: ./.github/opex_filters.yaml

  apply-management:
    needs: filter
    if: ${{ needs.filter.outputs.management == 'true' || needs.filter.outputs.apply-action == 'true' }}
    uses: ./.github/workflows/call_opex_api.yml
    name: (Public) Apply changes to Production
    secrets: inherit
    with:
      api_name: management
      app_name: functions-subscription