name: PR - Opex Dashboard trial-system

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - "apps/functions-subscription/api/*.yaml"
      - "infra/resources/modules/commons/api/**/*.yaml"
      - ".github/workflows/pr_opex_api_session_manager.yaml"
      - ".github/workflows/call_pr_opex_api.yml"
      - "apps/functions-subscription/.opex/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  filter:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    outputs:
      plan-action: ${{ steps.filter.outputs.plan-action }}
      management: ${{ steps.filter.outputs.management }}
      
    # Checks to see if openapi specs in the PR match one of the ones listed.
    # We can use the result to decide which job to run
    # With this type of filter we can avoid creating a lot of workflow files
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: ./.github/opex_filters.yaml
  plan-management:
    needs: filter
    if: ${{ needs.filter.outputs.management == 'true' || needs.filter.outputs.plan-action == 'true' }}
    uses: ./.github/workflows/call_pr_opex_api.yml
    name: (Public) Plan changes against Production
    secrets: inherit
    with:
        api_name: management
        app_name: functions-subscription