name: Release Infra

on:
  workflow_dispatch:
  push:
    tags:
      # Trigger this workflow when a tag `@infra/resources@<sem-ver>` is pushed.
      - '@infra/resources@[0-9]+.[0-9]+.[0-9]+'

jobs:
  release_prod:
    concurrency:
      cancel-in-progress: false
      group: terraform

    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Infrastructure Apply
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
